const topics = [
  'What is the one random word you always say?',
  'Do you believe in Reincarnation?',
  'What’s the best dream you’ve ever seen and always wish for it to repeat?',
  'What do you regret doing in life?',
  'What is something you never shared with any person?',
  'Who do you think has the easiest life in your friend group/family?',
  'If you had chance to ask God three questions, what they would be?',
  'Which is your favorite day of the week?',
  'When does life hits different for you?',
  'If you had choice to go to a party with your friends or stay home with food and good movies, which one would you choose on Friday night?',
  'If your life was a sitcom, which one it would be?',
  'If you could say one word for the rest of your life, what it would be',
  'What’s the most embarrassing moment you’ve ever had in public?',
  'If you had to remove one body part, which one would you choose?',
  'Who will you choose to kill, marry, kiss from your friend group?',
  'What’s the flavor of gum you wish existed?',
  'What animal would you want to be reincarnated as?',
  'Which foreign language would you like to learn?',
  'When was the last time you had a good belly laugh?',
  'What was the last reason you cried?',
  'What’s the joke you always tell to sad friends?',
  'What era would you choose to live in?',
  'Do you believe in aliens?',
  'If you had $1,000,000 only for an hour, how would you spend it?',
  'What do you wish someone has told to your teenage self?',
  'Which book impacted you the most?',
  'What’s the biggest lesson you’ve learnt in life?',
  'What food do you crave mostly?',
  'What was the last thing you’ve been overthinking about?',
  'Which is your comfort movie?',
  'Is there a celebrity couple which makes you believe in love so far?',
  'Have you ever had to scream “help” and why?',
  'What’s your weirdest habit?',
  'What’s the weirdest meal you’ve ever eaten?',
  'When have you felt most proud of yourself?',
  'What’s the biggest words someone has ever told to you?',
  'What are you the most grateful for?',
  'What is your love language?',
  'In your opinion, which aesthetic suits you the most?',
  'How would you describe humanity to aliens?',
  'What do you do when you can’t sleep?',
  'Have you ever stolen something from store?',
  'What’s the most embarrassing thing someone catch you doing?',
  'What would your parents say if they read your recent text messages?',
  'What do you think your biggest red flag is?',
  'What movie can you watch over and over again?',
  'What’s your greatest teen memory you’d want to tell your children about?',
  'What is wrong but sounds right?',
  'If you had to choose one social media for the rest of your life, which one would it be?',
  'If you could dis-invent one thing, what it would be?',
  'What’s the wildest thing you’ve ever done in hotel?',
  'When have you had your first hangover?',
  'Would you rather have an opportunity to copy/paste in real life or undo?',
  'Have you ever cried at a movie?',
  'Who from your past would you wish to stayed in your life?',
  'What do you notice first in new people?',
  'What’s the weirdest tattoo idea you’ve ever had?',
  'What are you looking forward to the most in next 1 year?',
  'What’s the craziest thing you’ve ever done?',
  'What habits are holding you back from success?',
  'What’s one thing no one knows about you?',
  'What was your instant thought during your first kiss?',
  'Have you ever chosen someone over your best friend?',
  'What’s your biggest fear?',
  'How many pancakes you can eat in a single sitting?',
  'Who would you choose to spend the best day in your life with?',
  'Would you rather read minds or travel in time?',
  'What is the best part of your personality?',
  'What is your secret talent?',
  'Which movie makes you cry every single time? - This is a last one'
];

export const getRandomTopic = () => {
  return topics[Math.floor(Math.random() * topics.length)];
};

